development:
  sessions:
    default:
      database: arch_serw_inter_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: arch_serw_inter_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
